# fly.toml file generated for wlc-laravel on 2023-01-21T19:06:22+01:00

app = "wlc-laravel"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[mounts]
  source="database_vol"
  destination="/var/www/html/database/database"

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MAIL_MAILER="smtp"
  MAIL_HOST="smtp-relay.sendinblue.com"
  MAIL_PORT="587"
  MAIL_ENCRYPTION="tls"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
