# fly.toml app configuration file generated for winterlauf on 2024-01-14T17:42:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "winterlauf"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"
console_command = "php /var/www/html/artisan tinker"

[experimental]
  auto_rollback = true

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[env]
  APP_DEBUG = "false"
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MAIL_ENCRYPTION = "tls"
  MAIL_HOST = "smtp-relay.sendinblue.com"
  MAIL_MAILER = "smtp"
  MAIL_PORT = "587"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[[mounts]]
  source = "database_vol"
  destination = "/var/www/html/database/database"
  initial_size = "1gb"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
